// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ClipController from "./clip_controller"
application.register("clip", ClipController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import LocationController from "./location_controller"
application.register("location", LocationController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import ShopIndexController from "./shop_index_controller"
application.register("shop-index", ShopIndexController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import ToastController from "./toast_controller"
application.register("toast", ToastController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)
